package permissao;

public enum Permissao {
    APROVAR_DESCONTO,
    CADASTRAR_FUNCIONARIO,
    CANCELAR_VENDA,
    ALTERAR_ESTOQUE,
    VISUALIZAR_RELATORIOS,
    REALIZAR_VENDA,
    APLICAR_DESCONTO_PADRAO,
    CONSULTAR_ESTOQUE,
    CADASTRAR_PRODUTO,
    APROVAR_PEDIDO,
    ATUALIZAR_ESTOQUE
}